### ISSUE TITLE
Bug + Sugestão na pesquisa.

### ISSUE THREAD

**Issue by Wuzuy** [FlugelSchwarz/Pokedex#1]
Estava testando o site em si, a dinâmica dele foi interessante, está funcionando muito bem. Entretanto constatei um bug e uma sugestão:

Bug: Quando colocado o nome de um personagem que não existe, a imagem some. Nisso que a imagem some, quando você volta a um pokemon existente ou uma seleção existente, a imagem não carrega, sendo necessário atualizar a página.

Sugestão: Colocar algum botão de pesquisa ou então um field avisando sobre a necessidade de apertar "ENTER" para pesquisar o Pokemon.

**Comment by Marmotinha-Dev** [comment]
Obrigado pelo seu feedback e sugestão. O bug já foi solucionado. Obrigado! ദ്ദി( • ᴗ - ) ✧

**Comment by Wuzuy** [comment]
Em relação a sugestão, foi feito algo que auxiliará muito a entenderem sobre o enter. Sobre o bug, ainda é recorrente:

![image](https://github.com/Marmotinha-Dev/Pokedex/assets/89390605/7e4503c3-fc2a-4117-8fb8-372f79489bc7)
